# Generated by Django 5.0.4 on 2026-05-15 10:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FraudAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fraud_probability", models.IntegerField(default=0)),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="LOW",
                        max_length=10,
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                ("indicators", models.JSONField(default=list)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ALLOW", "Allow"),
                            ("FLAG", "Flag"),
                            ("BLOCK", "Block"),
                        ],
                        default="ALLOW",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fraud_alert",
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "db_table": "fraud_alerts",
                "ordering": ["-created_at"],
            },
        ),
    ]
